### ISSUE TITLE
Make a Login Page

### ISSUE THREAD

**Issue by LAnastasiia** [dsc-ucu-lviv/hvalue#3]
- [x] 1. Draw a detailed template of the login page (must be consistent with general design). It's important to do have a fixed design before starting to work on its implementation

- [x] 2. Simple, but semantically correct implementation (in html)

- [ ] 3. Add styles (in css)

**Comment by sofiia-tesliuk** [comment]
**Functionality**
- [x] Check user password
- [x] Add user
