### ISSUE TITLE
Create the branbook

### ISSUE THREAD

**Issue by LAnastasiia** [dsc-ucu-lviv/hvalue#7]
Write a document with illustrative rules and styles for our project. These rules must later be strictly followed in design tasks (e.g.: in page design).

**Comment by sofiia-tesliuk** [comment]
Current version of the brandbook:
![image](https://drive.google.com/uc?export=view&id=1QGcZrEuzaJ5WtlIRiyzA59g4otsiIopn)
![image](https://drive.google.com/uc?export=view&id=18yItaVzFdHm-fLHOuXJ0-jrh1r76U6Gl)
